include:
  - local: '.gitlab-ci/yml/global.yml'
  - local: '.gitlab-ci/yml/matrix.yml'

stages:
  - bootstrap
  - build
  - check

bootstrap:
  stage: bootstrap
  extends: .bootstrap

build:
  stage: build
  extends: .build

check:
  stage: check
  extends:
    - .check
    - .test-matrix

# We know these checks will fail which are either false positives or
# real issues, in both cases it requires further debugging and fixes
check-allow-failure:
  stage: check
  extends:
    - .check
    - .test-matrix-allow-failure
  allow_failure: true

