include:
  - local: '.gitlab-ci/yml/global.yml'
  - local: '.gitlab-ci/yml/matrix.yml'

stages:
  - bootstrap
  - build
  - check

bootstrap:
  stage: bootstrap
  extends: .bootstrap

build-gcc:
  stage: build
  extends: .build

build-clang:
  stage: build
  extends:
    - .build-clang
    - .target-platform-clang-matrix

check:
  stage: check
  extends:
    - .check
    - .test-matrix
