default:
  image: quay.io/grub/debian-trixie-grub:2026-05-25.1

variables:
  SCRIPT_DIR: "./.gitlab-ci/script"

.bootstrap:
  script:
    - ./bootstrap
  artifacts:
    when: always
    untracked: true
    paths:
      - gnulib/

.build:
  dependencies:
    - bootstrap
  script:
    - $SCRIPT_DIR/build.sh
  artifacts:
    paths:
      - gnulib/
    untracked: true
    expire_in: 1 week
    when: always

.build-clang:
  dependencies:
    - bootstrap
  script:
    - $SCRIPT_DIR/build-clang.sh
  artifacts:
    paths:
      - gnulib/
    untracked: true
    expire_in: 1 week
    when: always

.check:
  script:
    - make --quiet TESTS=$TEST check
  dependencies:
    - build
  artifacts:
    untracked: true
    expire_in: 1 week
    when: always
