default:
  image: quay.io/grub/debian-trixie-grub:2026-05-25.1

variables:
  SCRIPT_DIR: "./.gitlab-ci/script"

.bootstrap:
  script:
    - ./bootstrap
  artifacts:
    when: always
    untracked: true
    paths:
      - gnulib/

.build:
  dependencies:
    - bootstrap
  script:
    - $SCRIPT_DIR/build.sh
  artifacts:
    paths:
      - gnulib/
    untracked: true
    expire_in: 1 week
    when: always

.build-clang:
  dependencies:
    - bootstrap
  script:
    - $SCRIPT_DIR/build-clang.sh
  artifacts:
    paths:
      - gnulib/
    untracked: true
    expire_in: 1 week
    when: always

.check:
  before_script:
    - |
      if [ ! -e /dev/loop-control ]; then
        mknod -m 0660 /dev/loop-control c 10 237 || :
      fi
      for i in $(seq 0 64); do
        [ -e "/dev/loop$i" ] || mknod -m 0660 "/dev/loop$i" b 7 "$i" || :
      done
      if [ -e /etc/init.d/zfs-fuse ]; then
        /etc/init.d/zfs-fuse start || :
      fi
  script:
    - make --quiet TESTS=$TEST check
  dependencies:
    - build
  artifacts:
    untracked: true
    expire_in: 1 week
    when: always
